### ISSUE TITLE
Amazing product.

### ISSUE THREAD

**Issue by carolgarette** [waseem18/gitpromote#3]
Thanks @waseem18 . That's an amazing product actually. By building it efficiently,it will serve the github community in a better way. :+1:

**Comment by SecUpwN** [comment]
I full agree with what @carolgarette said. @waseem18, if [THIS](https://www.gitpromote.appspot.com) is the website you've set up for your project, please add it to your repository here and make sure to fix the email notification feature on it. ;-)
