### ISSUE TITLE
Website: E-Mail subscription does not work

### ISSUE THREAD

**Issue by SecUpwN** [waseem18/gitpromote#4]
After entering an email on [Gitpromote](https://gitpromote.appspot.com/) and pressing `OKAY` doesn't do anything. Please fix it. Thank you!

**Comment by waseem18** [comment]
Actually I haven't updated the code. The site is actually running on an another URL. Because of few issues I haven't updated the code. I assure you that the site will run perfectly fine in a week at https://gitpromote.appspot.com . I will also update the code on GitHub within a week.
