### ISSUE TITLE
Remove incorrect gitpromote launch date

### ISSUE THREAD

**Issue by SecUpwN** [waseem18/gitpromote#5]
Hey @waseem18, I know that you're very busy with your final exams and stuff, but would you please take a minute to correct two things so that users actually know when `gitpromote` *really* launches?

1. The [gitpromote website](https://gitpromote.appspot.com/) says: `we are working on something very interesting! be notified. we just need your email` - please actually *enable* that email notification form. It currently does *nothing*. I had already filed this in #4, but you closed it with telling me: `I assure you that the site will run perfectly fine in a week `. Lesson: *Never* "ensure" anything to people that you can't keep! ;-)

2. Since https://github.com/waseem18/gitpromote/commit/f915dcc03ef99f208b4c01c84228df2ecd586f07 your `README` is telling people `Note: The product will be launched within a week!` - please *remove* that note, it is confusing and makes people disbelieve in your product.

* **Update:** I've just found [LFPR](https://github.com/deleteman/lfpr). Will your project be different? *Add uniqueness to yours!*

I'll be waiting patiently and would love to subscribe via E-Mail so that I won't have to nagg you again.

**Comment by waseem18** [comment]
@SecUpwN I have started working on gitpromote. You can subscribe for the Beta release here https://gitpromote.appspot.com/ . 

And yeah gitpromote will be unique :+1: 

Thanks for your patience. 

Will try to release it as soon as possible.
